services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
        PROJECT_NAME: '${APP_NAME}'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    networks:
      - project
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:${DB_PORT}'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'data_mysql:/var/lib/mysql'
    networks:
      - project 
networks:
  project:
    driver: bridge
volumes:
  data_mysql:
    driver: local


