services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
        PROJECT_NAME: '${APP_NAME}'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    networks:
      - project
    depends_on:
      - mysql
      - mongodb
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:${DB_PORT}'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'data_mysql:/var/lib/mysql'
    networks:
      - project
  mongodb:
    image: 'mongo'
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${DB_MONGO_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${DB_MONGO_PASSWORD}'
    ports:
        - '27017:${DB_MONGO_PORT}'
    volumes:
        - 'data_mongodb:/data/db'
    networks:
        - project
networks:
  project:
    driver: bridge
volumes:
  data_mysql:
    driver: local
  data_mongodb:
    driver: local


