services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
        PROJECT_NAME: '${APP_NAME}'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    networks:
      - project
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo'
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${DB_MONGO_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${DB_MONGO_PASSWORD}'
    ports:
        - '27017:${DB_MONGO_PORT}'
    volumes:
        - 'data_mongodb:/data/db'
    networks:
        - project
networks:
  project:
    driver: bridge
volumes:
  data_mongodb:
    driver: local


